
PackageIdentifier: SonicWALL.ConnectTunnel
PackageVersion: 12.4.1.991
PackageLocale: en-US
Publisher: SonicWall Inc.
PackageName: Connect Tunnel
License: SonicWALL, Inc. All rights reserved.
ShortDescription: SonicWALL Connect Tunnel VPN Client
ManifestType: defaultLocale
ManifestVersion: 1.0.0
